apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      name: myreactapp
      labels:
        app: react-app
    spec:
      containers:
        - name: myreact-app
          image: sendykris/myreactapp:tagVersion
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: svc-myreact-app
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80